# Generated by Django 4.1.7 on 2023-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(choices=[(50, 'C'), (54, 'C++'), (60, 'Go'), (62, 'Java'), (63, 'JavaScript'), (74, 'TypeScript'), (71, 'Python'), (72, 'Ruby'), (73, 'Rust')])),
                ('code', models.TextField()),
            ],
        ),
    ]
