# Generated by Django 4.1.7 on 2023-03-03 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeeditor',
            name='is_token_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codeeditor',
            name='stdout',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='codeeditor',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='codeeditor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeeditor',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='codeeditor',
            name='lang',
            field=models.IntegerField(choices=[(50, 'C'), (54, 'C++'), (60, 'Go'), (62, 'Java'), (63, 'JavaScript'), (74, 'TypeScript'), (71, 'Python'), (72, 'Ruby'), (73, 'Rust')], default=71),
        ),
    ]
