# Generated by Django 4.1.7 on 2023-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0002_codeeditor_is_token_used_codeeditor_stdout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeeditor',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
